---
# preprod Environment Configuration for haha
app_name: "haha"
environment: "preprod"
deploy_user: "liadwordpress"
server_ip: "192.99.35.79"

# Port Configuration
wordpress_port: 4100
phpmyadmin_port: 4101
mysql_port: 4120

# URLs
wp_url: "http://192.99.35.79:4100"
pma_url: "http://192.99.35.79:4101"

# WordPress Configuration
wordpress_title: "haha PreProd Site"
wordpress_admin_user: "admin"
wordpress_admin_email: "admin@haha-preprod.local"

# Database Configuration
mysql_database: "haha_preprod_db"
mysql_user: "haha_preprod_user"

# Application Settings
app_environment: "preprod"
debug_mode: false
cache_enabled: true

# Backup Configuration
backup_enabled: true
backup_retention_days: 14

# Security Settings
ssl_enabled: false
security_keys_salt: "preprod-security-keys"

# Performance Settings
php_memory_limit: "256M"
php_max_execution_time: 120
max_upload_size: "64M"
