services:
  database:
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    container_name: "haha_database"
    ports:
      - "4020:3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - haha_db_data:/var/lib/mysql
    networks:
      - haha_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: "haha_phpmyadmin"
    depends_on:
      - database
    ports:
      - "4001:80"
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - haha_network

  wordpress:
    image: wordpress:fpm
    restart: unless-stopped
    container_name: "haha_wordpress"
    depends_on:
      - database
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - haha_wp_data:/var/www/html
      # Split wp-content into separate mounts for better control
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      # Use persistent volume for plugins (not tracked in git)
      - haha_plugins:/var/www/html/wp-content/plugins
      # PHP configuration
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - haha_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: "haha_nginx"
    depends_on:
      - wordpress
    ports:
      - "4000:80"
    volumes:
      - haha_wp_data:/var/www/html:ro
      # Mirror the same wp-content mounts as wordpress
      - ./wp-content/themes:/var/www/html/wp-content/themes:ro
      - ./wp-content/uploads:/var/www/html/wp-content/uploads:ro
      - haha_plugins:/var/www/html/wp-content/plugins:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - haha_network

  wpcli:
    image: wordpress:cli
    container_name: "haha_wpcli"
    depends_on:
      - wordpress
      - database
    entrypoint: wp
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - haha_network
    volumes:
      - haha_wp_data:/var/www/html
      # Same wp-content mounts for WP-CLI access
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - haha_plugins:/var/www/html/wp-content/plugins

volumes:
  haha_db_data:
  haha_wp_data:
  haha_plugins:  # New persistent volume for plugins

networks:
  haha_network:
    driver: bridge